### ISSUE TITLE
Simple question..

### ISSUE THREAD

**Issue by Aka7tsu4** [mcNuggets1/mg_anticrash#2]
Hi. I’am not here to say an issue about this addons but i’am here to need help for making a new big update in the darkrp to optimize again completly the darkrp.
Please pull an update again for the darkrp, please optimize the darkrp..

**Comment by mcNuggets1** [comment]
DarkRP has a few optimisations problems, but still I am not the developer of DarkRP.
Ask FPtje about major optimisations to darkrp.

**Comment by Aka7tsu4** [comment]
Fpjte dont care about optimization, ur the only one
