### ISSUE TITLE
adv dupe 2 

### ISSUE THREAD

**Issue by SaintofDiablo** [mcNuggets1/mg_anticrash#4]
for some odd reason , if a user spawns a big base dupe , the anti crash deletes it or makes the  base fall apart

**Comment by mcNuggets1** [comment]
First,
Thanks for using my addons and for reporting an issue to issue tracker.

I'm gonna investigate in the issue and report back.

**Comment by mcNuggets1** [comment]
I couldn't find anything regarding your issue specifically.

Maybe related to MG.CheckForStuckingProps enabled.
I pushed a possible fix for you scenario. Please report back if it's fixed and if not, send me your configuration file.
