### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by SaintofDiablo** [mcNuggets1/mg_anticrash#5]
Ability to add to the MG.EntityDamageBlockList in game !

**Comment by mcNuggets1** [comment]
This would mean, we would have to network the table to every player joining.
This negates the whole effect of our anticrash being optimised for larger player bases.

Trust me.
Editing via file is slower, but in the end you don't want to influence player loading into your server long time just for 1 time configuration comfort.

**Comment by mcNuggets1** [comment]
This would mean, we have to network the MG.EntityDamageBlockList table to every player joining the game.
It would effect loading times of players in a negative way just for easier configuration.

The script has lua autorefresh support, that's enough for now. sorry.

**Comment by mcNuggets1** [comment]
You are free to add me on steam to talk to me about anything regarding the anticrash by the way.

https://steamcommunity.com/id/mcnuggets1908/
